"""create CRUD for CellarSlots and ScanEvents

Revision ID: 01a1f8d1295d
Revises: 05bc72e9f321
Create Date: 2025-07-05 16:54:22.878177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a1f8d1295d'
down_revision: Union[str, Sequence[str], None] = '05bc72e9f321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
