"""Add Wine model

Revision ID: 1824fbb79efa
Revises: 5b51dda9fd50
Create Date: 2025-07-03 17:15:34.325750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1824fbb79efa'
down_revision: Union[str, Sequence[str], None] = '5b51dda9fd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wines', sa.Column('country_id', sa.UUID(), nullable=False))
    op.add_column('wines', sa.Column('region_id', sa.UUID(), nullable=False))
    op.add_column('wines', sa.Column('subregion_id', sa.UUID(), nullable=False))
    op.add_column('wines', sa.Column('bottle_size', sa.Enum('PICCOLO', 'HALF', 'STANDARD', 'MAGNUM', 'JEROBOAM', 'REHOBOAM', 'METHUSELAH', 'SALMANAZAR', 'BALTHAZAR', 'NEBUCHADNEZZAR', 'MELCHIOR', 'OTHER', name='bottlesize'), nullable=False))
    op.add_column('wines', sa.Column('closure_type', sa.Enum('CORK', 'SYNTHETIC', 'SCREW_CAP', 'CROWN_CAP', 'OTHER', name='closuretype'), nullable=False))
    op.add_column('wines', sa.Column('abv', sa.DECIMAL(precision=4, scale=2), nullable=True))
    op.create_unique_constraint('uix_wine_unique', 'wines', ['producer', 'label', 'vintage', 'bottle_size'])
    op.create_foreign_key(None, 'wines', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'wines', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'wines', 'subregions', ['subregion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wines', type_='foreignkey')
    op.drop_constraint(None, 'wines', type_='foreignkey')
    op.drop_constraint(None, 'wines', type_='foreignkey')
    op.drop_constraint('uix_wine_unique', 'wines', type_='unique')
    op.drop_column('wines', 'abv')
    op.drop_column('wines', 'closure_type')
    op.drop_column('wines', 'bottle_size')
    op.drop_column('wines', 'subregion_id')
    op.drop_column('wines', 'region_id')
    op.drop_column('wines', 'country_id')
    # ### end Alembic commands ###
