"""Fix: add classifications table and classification_id to Wine

Revision ID: 4b8f035b9c59
Revises: 5766ff2bed15
Create Date: 2025-07-03 14:13:58.918961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8f035b9c59'
down_revision: Union[str, Sequence[str], None] = '5766ff2bed15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
