"""Fix: add classifications table and classification_id to Wine

Revision ID: 4b8f035b9c59
Revises: 5766ff2bed15
Create Date: 2025-07-03 14:13:58.918961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8f035b9c59'
down_revision: Union[str, Sequence[str], None] = '5766ff2bed15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'classifications',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('country_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('region_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['country_id'],['countries.id']),
        sa.ForeignKeyConstraint(['region_id'], ['regions.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'country_id', 'region_id', name='uix_classification_name_scope')
    )

    op.add_column(
        'wines',
        sa.Column('classification_id', postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        'fk_wine_classification',
        'wines',
        'classifications',
        ['classification_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
