"""Add id, producer, label, vintage to Wine

Revision ID: 5000d139b044
Revises: 4b8f035b9c59
Create Date: 2025-07-03 14:34:28.758280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5000d139b044'
down_revision: Union[str, Sequence[str], None] = '4b8f035b9c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
