"""Add Classification lookup table and link to Wine

Revision ID: 5766ff2bed15
Revises: 223ba791d3b0
Create Date: 2025-07-03 14:00:35.279981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5766ff2bed15'
down_revision: Union[str, Sequence[str], None] = '223ba791d3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
