"""Add Varietal model and wine_varietals association

Revision ID: 5b51dda9fd50
Revises: a23498f906ca
Create Date: 2025-07-03 15:47:58.823198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b51dda9fd50'
down_revision: Union[str, Sequence[str], None] = 'a23498f906ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('varietals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wine_varietals',
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('varietal_id', sa.UUID(), nullable=False),
    sa.Column('blend_pct', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['varietal_id'], ['varietals.id'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id'], ),
    sa.PrimaryKeyConstraint('wine_id', 'varietal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine_varietals')
    op.drop_table('varietals')
    # ### end Alembic commands ###
