"""add critic and quality models

Revision ID: a37a388b68d1
Revises: 86e5d9968512
Create Date: 2025-07-04 12:22:00.338533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37a388b68d1'
down_revision: Union[str, Sequence[str], None] = '86e5d9968512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critic_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wine_metrics',
    sa.Column('wine_id', sa.UUID(), nullable=False),
    sa.Column('avg_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('current_market', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rarity_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('qpr', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id'], ),
    sa.PrimaryKeyConstraint('wine_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wine_metrics')
    op.drop_table('critic_scores')
    # ### end Alembic commands ###
